Repository ByteBuildersLabs/ByteBeastsFrontend, pull requests merged in 2024-12, with the labels that each got.

#154 New character design: Dragon theme babybeast
  Assets/BabySprites/babybeast dragon bathing.gif
  Assets/BabySprites/babybeast dragon playing.gif
  Assets/BabySprites/babybeast dragon sleeping.gif
  Assets/BabySprites/babybeast new dragon.gif
  Assets/BabySprites/babybeast new dragon1.png
Labels: ODHack10

#152 New character design: Dark theme babybeast
  Assets/BabySprites/babybeast-dark-magic-theme-base.gif
  Assets/BabySprites/babybeast-dark-magic-theme-base.png
  Assets/BabySprites/babybeast-sprite-eat.gif
  Assets/BabySprites/babybeast-sprite-shower.gif
  Assets/BabySprites/babybeast-sprite-sleep.gif
Labels: ODHack10

#151 New character design: Crystal theme babybeast
  Assets/BabySprites/crystalbabybeast-eat.gif
  Assets/BabySprites/crystalbabybeast-eat.png
  Assets/BabySprites/crystalbabybeast-play-sprite.png
  Assets/BabySprites/crystalbabybeast-play.gif
  Assets/BabySprites/crystalbabybeast-shower-sprite.png
  Assets/BabySprites/crystalbabybeast-shower.gif
  Assets/BabySprites/crystalbabybeast-sleep-sprite.png
  Assets/BabySprites/crystalbabybeast-sleep.gif
  Assets/BabySprites/crystalbabybeast-sprite.png
  Assets/BabySprites/crystalbabybeast.gif
  Assets/BabySprites/crystalbabybeast_design.png
Labels: ODHack10

#153 New character design: Light theme babybeast
  Assets/BabySprites/babybeast light.gif
  Assets/BabySprites/babybeast light.png
  Assets/BabySprites/babybeast-eat light-export.gif
Labels: ODHack10

#166 prepare odhack 11
  README.md
Labels: core-dev

#168 Rename BabySprite files
  Assets/BabySprites/Bunny-Flame-Eat.gif
  Assets/BabySprites/Bunny-Flame-Eat.gif.meta
  Assets/BabySprites/Bunny-Flame-Idle.png
  Assets/BabySprites/Bunny-Flame-Idle.png.meta
  Assets/BabySprites/Bunny-Flame-Play.gif
  Assets/BabySprites/Bunny-Flame-Play.gif.meta
  Assets/BabySprites/Bunny-Flame-Shower.gif
  Assets/BabySprites/Bunny-Flame-Shower.gif.meta
  Assets/BabySprites/Bunny-Flame-Sleep.gif
  Assets/BabySprites/Bunny-Flame-Sleep.gif.meta
  Assets/BabySprites/Bunny-Gold-Eat.gif
  Assets/BabySprites/Dragon-Flame-Idle.gif
  Assets/BabySprites/Dragon-Flame-Idle.png
  Assets/BabySprites/Dragon-Flame-Play.gif
  Assets/BabySprites/Dragon-Flame-Shower.gif
  Assets/BabySprites/Dragon-Flame-Sleep.gif
  Assets/BabySprites/Fox-DarkMagic-Eat.gif
  Assets/BabySprites/Fox-DarkMagic-Run.gif
  Assets/BabySprites/Fox-DarkMagic-Run.png
  Assets/BabySprites/Fox-DarkMagic-Shower.gif
  Assets/BabySprites/Fox-DarkMagic-Sleep.gif
  Assets/BabySprites/Penguin-Crystal-Eat-Scene.png
  Assets/BabySprites/Penguin-Crystal-Eat.gif
  Assets/BabySprites/Penguin-Crystal-Idle-Scene.png
  Assets/BabySprites/Penguin-Crystal-Idle.gif
  Assets/BabySprites/Penguin-Crystal-Idle.png
  Assets/BabySprites/Penguin-Crystal-Play-Scene.png
  Assets/BabySprites/Penguin-Crystal-Play.gif
  Assets/BabySprites/Penguin-Crystal-Shower-Scene.png
  Assets/BabySprites/Penguin-Crystal-Shower.gif
  Assets/BabySprites/Penguin-Crystal-Sleep-Scene.png
  Assets/BabySprites/Penguin-Crystal-Sleep.gif
  Assets/BabySprites/Sheep-Lumos-Idle.gif
  Assets/BabySprites/Sheep-Lumos-Idle.png
Labels: actual: 1, XS, non rewarded, ODHack11

#167 docs: add issue template
  .DS_Store
  .github/ISSUE_TEMPLATE.md
Labels: actual: 1, XS, non rewarded, ODHack11, Maintainer - Luis

#170 feat: add new character: Baby Fire horse
  Assets/BabySprites/BabyHorse-Fire-Bath.gif
  Assets/BabySprites/BabyHorse-Fire-Eat.gif
  Assets/BabySprites/BabyHorse-Fire-Happy.gif
  Assets/BabySprites/BabyHorse-Fire-Idle.gif
  Assets/BabySprites/BabyHorse-Fire-Sleep.gif
Labels: enhancement, actual: 3, M, ODHack11, Maintainer - Luis

#171 feat: add new baby butterfly light theme
  Assets/BabySprites/Butterfly-light-Bath.gif
  Assets/BabySprites/Butterfly-light-Eat.gif
  Assets/BabySprites/Butterfly-light-Happy.gif
  Assets/BabySprites/Butterfly-light-Idle.gif
  Assets/BabySprites/Butterfly-light-Sleep.gif
Labels: ODHack11, Maintainer - JuanDi

#169 babybeast dark theme wolf pup
  Assets/BabySprites/BabyWolf-Dark- jump.gif
  Assets/BabySprites/BabyWolf-Dark-Eat.gif
  Assets/BabySprites/BabyWolf-Dark-idle.gif
  Assets/BabySprites/BabyWolf-Dark-shower.gif
  Assets/BabySprites/BabyWolf-Dark-sleep.gif
Labels: actual: 3, M, ODHack11, Maintainer - Luis

#174 Baby eagle animations #172
  Assets/BabySprites/BabyEagle-Crystal-eat.gif
  Assets/BabySprites/BabyEagle-Crystal-happy.gif
  Assets/BabySprites/BabyEagle-Crystal-idle.gif
  Assets/BabySprites/BabyEagle-Crystal-sleep.gif
  Assets/BabySprites/BabyEagle-crystal-bath.gif
Labels: actual: 3, M, ODHack11, Maintainer - JuanDi
