Repository ByteBuildersLabs/ByteBeastsFrontend, pull requests merged in 2024-11, with the labels that each got.

#105 feat: Add home button
  Assets/Battle Assets/Art/UI/Home_Buttom.meta
  Assets/Battle Assets/Art/UI/Home_Buttom/ui_icons_blue_home.png
  Assets/Battle Assets/Art/UI/Home_Buttom/ui_icons_blue_home.png.meta
  Assets/Battle Assets/Art/UI/Panel_Assets.meta
  Assets/Battle Assets/Art/UI/Panel_Assets/.DS_Store
  Assets/Battle Assets/Art/UI/Panel_Assets/size_L.meta
  Assets/Battle Assets/Art/UI/Panel_Assets/size_L/.DS_Store
  Assets/Battle Assets/Art/UI/Panel_Assets/size_L/skin_l_solid_mono_1.png
  Assets/Battle Assets/Art/UI/Panel_Assets/size_L/skin_l_solid_mono_1.png.meta
  Assets/Battle Assets/Art/UI/Panel_Assets/size_M.meta
  Assets/Battle Assets/Art/UI/Panel_Assets/size_M/.DS_Store
  Assets/Battle Assets/Art/UI/Panel_Assets/size_M/skin_m_solid_mono_1.png
  Assets/Battle Assets/Art/UI/Panel_Assets/size_M/skin_m_solid_mono_1.png.meta
  Assets/Battle Assets/Art/UI/Panel_Assets/size_s.meta
  Assets/Battle Assets/Art/UI/Panel_Assets/size_s/.DS_Store
  Assets/Battle Assets/Art/UI/Panel_Assets/size_s/skin_s_solid_mono_1.png
  Assets/Battle Assets/Art/UI/Panel_Assets/size_s/skin_s_solid_mono_1.png.meta
  Assets/Prefabs/UI Canvas.prefab
  Assets/Scripts/GameMenu.cs
Labels: ODHack 9

#103 Feat: Change gameplay panel assets
  Assets/Battle Assets/Art/UI/Battle_Panel_Red_L.png
  Assets/Battle Assets/Art/UI/Battle_Panel_Red_L.png.meta
  Assets/Battle Assets/Art/UI/Battle_Panel_Red_M.png
  Assets/Battle Assets/Art/UI/Battle_Panel_Red_M.png.meta
  Assets/Battle Assets/Art/UI/Battle_Panel_Red_S.png
  Assets/Battle Assets/Art/UI/Battle_Panel_Red_S.png.meta
  Assets/Prefabs/BattleManager.prefab
  Assets/Prefabs/UI Canvas.prefab
Labels: ODHack 9

#119 feat: fix rain bug
  Assets/RainMaker/Prefab/RainScript2D.cs
Labels: ODHack 9

#121 feat: add animation fountain
  Assets/Animations/Fountain Animation.meta
  Assets/Animations/Fountain Animation/Fountain animation.png
  Assets/Animations/Fountain Animation/Fountain animation.png.meta
  Assets/Animations/Fountain Animation/fountain 1.controller
  Assets/Animations/Fountain Animation/fountain 1.controller.meta
  Assets/Animations/Fountain Animation/fountain anim.anim
  Assets/Animations/Fountain Animation/fountain anim.anim.meta
  Assets/Animations/Fountain Animation/fountain.controller
  Assets/Animations/Fountain Animation/fountain.controller.meta
  Assets/Scenes/Town.unity
Labels: ODHack 9

#123 feat: add animation torch and grave
  Assets/Animations/TorchAnimation.meta
  Assets/Animations/TorchAnimation/Animator.meta
  Assets/Animations/TorchAnimation/Animator/GraveAnim.anim
  Assets/Animations/TorchAnimation/Animator/GraveAnim.anim.meta
  Assets/Animations/TorchAnimation/Animator/TorchAnimation.anim
  Assets/Animations/TorchAnimation/Animator/TorchAnimation.anim.meta
  Assets/Animations/TorchAnimation/Controller.meta
  Assets/Animations/TorchAnimation/Controller/FireAnim_0.controller
  Assets/Animations/TorchAnimation/Controller/FireAnim_0.controller.meta
  Assets/Animations/TorchAnimation/Controller/TorchAnim_0.controller
  Assets/Animations/TorchAnimation/Controller/TorchAnim_0.controller.meta
  Assets/Animations/TorchAnimation/Sprites.meta
  Assets/Animations/TorchAnimation/Sprites/FireAnim.png
  Assets/Animations/TorchAnimation/Sprites/FireAnim.png.meta
  Assets/Animations/TorchAnimation/Sprites/TorchAnim.png
  Assets/Animations/TorchAnimation/Sprites/TorchAnim.png.meta
  Assets/Scenes/DarkForest.unity
  ProjectSettings/TagManager.asset
Labels: ODHack 9

#134 add inner house scene
  Assets/Battle Assets/.DS_Store
  Assets/Battle Assets/Art/Cave Assets/Inner_Padded.png.meta
  Assets/Battle Assets/Art/Cave Assets/ground-1.asset
  Assets/Battle Assets/Art/Cave Assets/ground-1.asset.meta
  Assets/Battle Assets/Art/Cave Assets/ground-2.asset
  Assets/Battle Assets/Art/Cave Assets/ground-2.asset.meta
  Assets/Prefabs/Area Exit.prefab
  Assets/Scenes/House1.unity
  Assets/Scenes/House1.unity.meta
  Assets/Scenes/Town.unity
  Assets/Tiles/Inner.prefab
  Assets/TownSprites/HousesTiles/WallsD.png.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement, core-dev

#145 Prepare repo for ODHack10
  Assets/BabySprites.meta
  Assets/BabySprites/babybeast resize.png
  Assets/BabySprites/babybeast resize.png.meta
  Assets/BabySprites/babybeast-eat-resize.gif
  Assets/BabySprites/babybeast-eat-resize.gif.meta
  Assets/BabySprites/babybeast-play-export.gif
  Assets/BabySprites/babybeast-play-export.gif.meta
  Assets/BabySprites/babybeast-shower-export.gif
  Assets/BabySprites/babybeast-shower-export.gif.meta
  Assets/BabySprites/babybeast-sleep-export.gif
  Assets/BabySprites/babybeast-sleep-export.gif.meta
  Assets/Scenes/DarkForest.unity
  Assets/Tiles/corners.prefab
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-20.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-20.asset.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-21.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-21.asset.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-22.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-22.asset.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-23.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-23.asset.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-24.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-24.asset.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-25.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-25.asset.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-26.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-26.asset.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-27.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-27.asset.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-28.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-28.asset.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-29.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-29.asset.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-30.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-30.asset.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-31.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/cave-ground-31.asset.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/grounds.png.meta
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/grounds_730.asset
  Assets/World Assets/Jungle - Rogue Adventure/Jungle - Rogue Adventure/32x32/grounds_730.asset.meta
  README.md
Labels: core-dev

#148 enhanced dark forest floor
  Assets/Scenes/DarkForest.unity
Labels: ODHack10, approved
