Repository ByteBuildersLabs/ByteBeastsFrontend, pull requests merged in 2024-10, with the labels that each got.

#78 Update readme.md file
  .DS_Store
  Gameplay/battle1.png
  Gameplay/battle2.png
  Gameplay/forest1.png
  Gameplay/forest2.png
  Gameplay/forest3.png
  Gameplay/town1.png
  Gameplay/town2.png
  Gameplay/town3.png
  Maintainers/.DS_Store
  Maintainers/JuanDi.jpeg
  Maintainers/Luis.jpeg
  Maintainers/LuisEverai.png
  Maintainers/juandiEverai.jpeg
  README.md
Labels: documentation, internal-contributor

#82 Remove objects from the forest scene
  Assets/Scenes/Countryside.unity
Labels: invalid, internal-contributor

#83 Bugs: Layers with trees, flowers, skeletons, graves and stones
  .DS_Store
  Assets/.DS_Store
  Assets/Scenes/.DS_Store
  Assets/Scenes/Countryside.unity
  Assets/Scenes/Town.unity
Labels: bug, internal-contributor

#90 Change Battle Background
  Assets/Battle Assets/Art/.DS_Store
  Assets/Battle Assets/Art/Backgrounds/.DS_Store
  Assets/Battle Assets/Art/Backgrounds/DarkForest-3.jpg
  Assets/Battle Assets/Art/Backgrounds/DarkForest-3.jpg.meta
  Assets/Battle Assets/Art/Backgrounds/darkforest.jpg
  Assets/Battle Assets/Art/Backgrounds/darkforest.jpg.meta
  Assets/Battle Assets/Art/Backgrounds/darkorest background.png
  Assets/Battle Assets/Art/Backgrounds/darkorest background.png.meta
  Assets/Prefabs/BattleManager.prefab
  Assets/Scenes/Cave.unity
Labels: enhancement, internal-contributor

#104 docs: add documentation to c# scripts
  Assets/Scripts/AreaEntrance.cs
  Assets/Scripts/AreaExit.cs
  Assets/Scripts/AttackEffect.cs
  Assets/Scripts/AudioManager.cs
  Assets/Scripts/BAttleType.cs
  Assets/Scripts/BattleChar.cs
  Assets/Scripts/BattleMagicSelect.cs
  Assets/Scripts/BattleManager.cs
  Assets/Scripts/BattleMove.cs
  Assets/Scripts/BattleNotification.cs
  Assets/Scripts/BattleReward.cs
  Assets/Scripts/BattleStarter.cs
  Assets/Scripts/BattleTargetButton.cs
  Assets/Scripts/CameraController.cs
  Assets/Scripts/CharStats.cs
  Assets/Scripts/DamageNumber.cs
  Assets/Scripts/DestroyOverLifetime.cs
  Assets/Scripts/DialogActivator.cs
  Assets/Scripts/DialogManager.cs
  Assets/Scripts/EssentialsLoader.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/GameMenu.cs
  Assets/Scripts/GameOver.cs
  Assets/Scripts/Item.cs
  Assets/Scripts/ItemButton.cs
  Assets/Scripts/LoadingScene.cs
  Assets/Scripts/MainMenu.cs
  Assets/Scripts/PickupItem.cs
  Assets/Scripts/PlayerController.cs
  Assets/Scripts/PlayerLoader.cs
  Assets/Scripts/QuestManager.cs
  Assets/Scripts/QuestMarker.cs
  Assets/Scripts/QuestObjectActivator.cs
  Assets/Scripts/Shop.cs
  Assets/Scripts/ShopKeeper.cs
  Assets/Scripts/Singleton.cs
  Assets/Scripts/UIFade.cs
Labels: ODHack 9

#111 docs: add template for Pull Request
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ODHack 9

#113 fix-CharImage
  Assets/Scripts/GameMenu.cs
Labels: bug, core-dev
