Repository ByteBuildersLabs/ByteBeastsFrontend, pull requests merged in 2024-09, with the labels that each got.

#40 Refector ByteBeasts Frontend Repo - Tutorial_Info
  Assets/CreatorKitRPG_Third-PartyNotice.txt
  Assets/CreatorKitRPG_Third-PartyNotice.txt.meta
  Assets/TutorialInfo.meta
  Assets/TutorialInfo/Icons.meta
  Assets/TutorialInfo/Icons/Help_Icon.png
  Assets/TutorialInfo/Icons/Help_Icon.png.meta
  Assets/TutorialInfo/Icons/icon_tutorial_package.png
  Assets/TutorialInfo/Icons/icon_tutorial_package.png.meta
  Assets/TutorialInfo/Layout.wlt
  Assets/TutorialInfo/Layout.wlt.meta
  Assets/TutorialInfo/Scripts.meta
  Assets/TutorialInfo/Scripts/Editor.meta
  Assets/TutorialInfo/Scripts/Editor/ReadmeEditor.cs
  Assets/TutorialInfo/Scripts/Editor/ReadmeEditor.cs.meta
  Assets/TutorialInfo/Scripts/Readme.cs
  Assets/TutorialInfo/Scripts/Readme.cs.meta
Labels: invalid

#54 feat: fix bridge bug v2
  Assets/Scenes/Countryside.unity
Labels: bug

#57 Add some Non Player Character into the map
  .DS_Store
  Assets/.DS_Store
  Assets/Animations/NPC_Animations.meta
  Assets/Animations/NPC_Animations/VillagerWalkRight.meta
  Assets/Animations/NPC_Animations/VillagerWalkRight/Villager.anim
  Assets/Animations/NPC_Animations/VillagerWalkRight/Villager.anim.meta
  Assets/Animations/NPC_Animations/VillagerWalkRight/Walk_Right_1.controller
  Assets/Animations/NPC_Animations/VillagerWalkRight/Walk_Right_1.controller.meta
  Assets/Character.meta
  Assets/Character/.DS_Store
  Assets/Character/NPC.meta
  Assets/Character/NPC/.DS_Store
  Assets/Character/NPC/Villager.meta
  Assets/Character/NPC/Villager/SeparateAnim.meta
  Assets/Character/NPC/Villager/SeparateAnim/Attack.png
  Assets/Character/NPC/Villager/SeparateAnim/Attack.png.meta
  Assets/Character/NPC/Villager/SeparateAnim/Dead.png
  Assets/Character/NPC/Villager/SeparateAnim/Dead.png.meta
  Assets/Character/NPC/Villager/SeparateAnim/Idle.png
  Assets/Character/NPC/Villager/SeparateAnim/Idle.png.meta
  Assets/Character/NPC/Villager/SeparateAnim/Item.png
  Assets/Character/NPC/Villager/SeparateAnim/Item.png.meta
  Assets/Character/NPC/Villager/SeparateAnim/Jump.png
  Assets/Character/NPC/Villager/SeparateAnim/Jump.png.meta
  Assets/Character/NPC/Villager/SeparateAnim/Special1.png
  Assets/Character/NPC/Villager/SeparateAnim/Special1.png.meta
  Assets/Character/NPC/Villager/SeparateAnim/Special2.png
  Assets/Character/NPC/Villager/SeparateAnim/Special2.png.meta
  Assets/Character/NPC/Villager/SeparateAnim/Walk.png
  Assets/Character/NPC/Villager/SeparateAnim/Walk.png.meta
  Assets/Scenes/Countryside.unity
  Assets/Scripts/Waypoint.meta
  Assets/Scripts/Waypoint/Editor.meta
  Assets/Scripts/Waypoint/Editor/WaypointEditor.cs
  Assets/Scripts/Waypoint/Editor/WaypointEditor.cs.meta
  Assets/Scripts/Waypoint/Waypoint.cs
  Assets/Scripts/Waypoint/Waypoint.cs.meta
Labels: enhancement

#58 Add interactions with each Non Player Character - Walk
  .DS_Store
  Assets/.DS_Store
  Assets/Animations/NPC_Animations/WomanWalkDown.anim
  Assets/Animations/NPC_Animations/WomanWalkDown.anim.meta
  Assets/Animations/NPC_Animations/WomanWalkUp.anim
  Assets/Animations/NPC_Animations/WomanWalkUp.anim.meta
  Assets/Animations/NPC_Animations/Woman_WalkDown_1.controller
  Assets/Animations/NPC_Animations/Woman_WalkDown_1.controller.meta
  Assets/Character/NPC/.DS_Store
  Assets/Character/NPC/Woman.meta
  Assets/Character/NPC/Woman/.DS_Store
  Assets/Character/NPC/Woman/Faceset.png
  Assets/Character/NPC/Woman/Faceset.png.meta
  Assets/Character/NPC/Woman/SeparateAnim.meta
  Assets/Character/NPC/Woman/SeparateAnim/Attack.png
  Assets/Character/NPC/Woman/SeparateAnim/Attack.png.meta
  Assets/Character/NPC/Woman/SeparateAnim/Dead.png
  Assets/Character/NPC/Woman/SeparateAnim/Dead.png.meta
  Assets/Character/NPC/Woman/SeparateAnim/Idle.png
  Assets/Character/NPC/Woman/SeparateAnim/Idle.png.meta
  Assets/Character/NPC/Woman/SeparateAnim/Item.png
  Assets/Character/NPC/Woman/SeparateAnim/Item.png.meta
  Assets/Character/NPC/Woman/SeparateAnim/Jump.png
  Assets/Character/NPC/Woman/SeparateAnim/Jump.png.meta
  Assets/Character/NPC/Woman/SeparateAnim/Special1.png
  Assets/Character/NPC/Woman/SeparateAnim/Special1.png.meta
  Assets/Character/NPC/Woman/SeparateAnim/Special2.png
  Assets/Character/NPC/Woman/SeparateAnim/Special2.png.meta
  Assets/Character/NPC/Woman/SeparateAnim/Walk.png
  Assets/Character/NPC/Woman/SeparateAnim/Walk.png.meta
  Assets/Scenes/Countryside.unity
  Assets/Scripts/Waypoint/.DS_Store
  Assets/Scripts/Waypoint/NPCMovement.cs
  Assets/Scripts/Waypoint/NPCMovement.cs.meta
  Assets/Scripts/Waypoint/Waypoint.cs
  Assets/Scripts/Waypoint/WaypointMovement.cs
  Assets/Scripts/Waypoint/WaypointMovement.cs.meta
Labels: enhancement

#61 feat: fix npc touchscreen issue
  Assets/Scripts/Dialogue/DialogueManager.cs
Labels: bug

#65 Bug: dimensions of the npc's dialog panel when he is speaking collides with the joystick
  Assets/Scenes/Countryside.unity
Labels: bug

#66 Improve battle rewards
  Assets/Prefabs/UI Canvas.prefab
  Assets/Scripts/BattleReward.cs
Labels: enhancement

#69 feat: fix colliders with trees
  Assets/Scenes/Countryside.unity
  Assets/WebGLTemplates.meta
  ProjectSettings/TagManager.asset
Labels: bug
